services:
  zone-configurator:
    image: everythingsmarthome/everything-presence-mmwave-configurator:latest
    container_name: everything-presence-mmwave-configurator
    restart: unless-stopped
    ports:
      - "${APP_PORT:-42069}:42069"
      - "${FIRMWARE_LAN_PORT:-38080}:${FIRMWARE_LAN_PORT:-38080}"
    environment:
      HA_BASE_URL: "${HA_BASE_URL:-http://homeassistant.local:8123}"
      HA_LONG_LIVED_TOKEN: "${HA_LONG_LIVED_TOKEN}"
      FIRMWARE_LAN_PORT: "${FIRMWARE_LAN_PORT:-38080}"
    volumes:
      - ./config:/config

# Uncomment the lines below and replace the volume mount above with "- epzone-config:/config" if you want to used a named volume instead. 
#volumes:
#    epzone-config:
#        driver: local
