services:
  zone-configurator:
    image: everythingsmarthome/everything-presence-mmwave-configurator:latest
    container_name: everything-presence-mmwave-configurator
    restart: unless-stopped
    ports:
      - "42069:42069"
      - "38080:38080"
    environment:
      HA_BASE_URL: "http://homeassistant.local:8123"
      HA_LONG_LIVED_TOKEN: "REPLACE_WITH_LONG_LIVED_TOKEN"
      FIRMWARE_LAN_PORT: "38080"
    volumes:
      - ./config:/config
